--- 
before_script: 
  - "npm install -g @vue/cli"
cache: 
  directories: 
    - node_modules
dist: trusty
dotnet: "2.1.403"
install: 
  - "dotnet restore"
  - "npm install --prefix ./src/EllaX.UI.Web/ClientApp"
language: csharp
mono: none
node_js: 
  - iojs
  - "8"
script: 
  - "dotnet build"
solution: EllaX.sln
